@echo off
title "MAMEoXtras_[Mar-20-2023].xml" ^| Build: Mon 03/20/2023
echo.=====================================================
echo. This script will MOVE matched .zip files   
echo.=====================================================
choice /m "Continue?"
if %errorlevel% equ 2 exit
cls&echo. Creating folders and moving files...
md mahjong
>nul 2>&1 move /y 47pie2.zip .\mahjong\
>nul 2>&1 move /y 47pie2o.zip .\mahjong\
>nul 2>&1 move /y 7jigen.zip .\mahjong\
>nul 2>&1 move /y 7toitsu.zip .\mahjong\
>nul 2>&1 move /y akiss.zip .\mahjong\
>nul 2>&1 move /y apparel.zip .\mahjong\
>nul 2>&1 move /y av2mj1bb.zip .\mahjong\
>nul 2>&1 move /y av2mj2rg.zip .\mahjong\
>nul 2>&1 move /y bakatono.zip .\mahjong\
>nul 2>&1 move /y bakuhatu.zip .\mahjong\
>nul 2>&1 move /y bananadr.zip .\mahjong\
>nul 2>&1 move /y bijokkog.zip .\mahjong\
>nul 2>&1 move /y bijokkoy.zip .\mahjong\
>nul 2>&1 move /y ccasino.zip .\mahjong\
>nul 2>&1 move /y chinmoku.zip .\mahjong\
>nul 2>&1 move /y citylove.zip .\mahjong\
>nul 2>&1 move /y club90s.zip .\mahjong\
>nul 2>&1 move /y club90sa.zip .\mahjong\
>nul 2>&1 move /y cmehyou.zip .\mahjong\
>nul 2>&1 move /y crystal2.zip .\mahjong\
>nul 2>&1 move /y crystalg.zip .\mahjong\
>nul 2>&1 move /y daireika.zip .\mahjong\
>nul 2>&1 move /y daiyogen.zip .\mahjong\
>nul 2>&1 move /y dakkochn.zip .\mahjong\
>nul 2>&1 move /y dokyusei.zip .\mahjong\
>nul 2>&1 move /y dokyusp.zip .\mahjong\
>nul 2>&1 move /y dondenmj.zip .\mahjong\
>nul 2>&1 move /y ejanhs.zip .\mahjong\
>nul 2>&1 move /y finalbny.zip .\mahjong\
>nul 2>&1 move /y fromanc2.zip .\mahjong\
>nul 2>&1 move /y fromanc4.zip .\mahjong\
>nul 2>&1 move /y fromance.zip .\mahjong\
>nul 2>&1 move /y fromancr.zip .\mahjong\
>nul 2>&1 move /y gakusai.zip .\mahjong\
>nul 2>&1 move /y gakusai2.zip .\mahjong\
>nul 2>&1 move /y gal10ren.zip .\mahjong\
>nul 2>&1 move /y galkaika.zip .\mahjong\
>nul 2>&1 move /y galkoku.zip .\mahjong\
>nul 2>&1 move /y grtwall.zip .\mahjong\
>nul 2>&1 move /y hanamai.zip .\mahjong\
>nul 2>&1 move /y hanamomo.zip .\mahjong\
>nul 2>&1 move /y hgkairak.zip .\mahjong\
>nul 2>&1 move /y hnfubuki.zip .\mahjong\
>nul 2>&1 move /y hnkochou.zip .\mahjong\
>nul 2>&1 move /y hotgmck.zip .\mahjong\
>nul 2>&1 move /y hotgmck3.zip .\mahjong\
>nul 2>&1 move /y hourouki.zip .\mahjong\
>nul 2>&1 move /y housemn2.zip .\mahjong\
>nul 2>&1 move /y housemnq.zip .\mahjong\
>nul 2>&1 move /y hyouban.zip .\mahjong\
>nul 2>&1 move /y hypreac2.zip .\mahjong\
>nul 2>&1 move /y hypreact.zip .\mahjong\
>nul 2>&1 move /y idhimitu.zip .\mahjong\
>nul 2>&1 move /y idolmj.zip .\mahjong\
>nul 2>&1 move /y iemoto.zip .\mahjong\
>nul 2>&1 move /y imekura.zip .\mahjong\
>nul 2>&1 move /y janjans1.zip .\mahjong\
>nul 2>&1 move /y janshin.zip .\mahjong\
>nul 2>&1 move /y jantouki.zip .\mahjong\
>nul 2>&1 move /y jjparad2.zip .\mahjong\
>nul 2>&1 move /y jjparads.zip .\mahjong\
>nul 2>&1 move /y jogakuen.zip .\mahjong\
>nul 2>&1 move /y kaguya.zip .\mahjong\
>nul 2>&1 move /y kakumei.zip .\mahjong\
>nul 2>&1 move /y kakumei2.zip .\mahjong\
>nul 2>&1 move /y kanatuen.zip .\mahjong\
>nul 2>&1 move /y kirarast.zip .\mahjong\
>nul 2>&1 move /y kisekaem.zip .\mahjong\
>nul 2>&1 move /y kiwame.zip .\mahjong\
>nul 2>&1 move /y kiwames.zip .\mahjong\
>nul 2>&1 move /y koinomp.zip .\mahjong\
>nul 2>&1 move /y korinai.zip .\mahjong\
>nul 2>&1 move /y lemnangl.zip .\mahjong\
>nul 2>&1 move /y mahmajn.zip .\mahjong\
>nul 2>&1 move /y mahmajn2.zip .\mahjong\
>nul 2>&1 move /y mahretsu.zip .\mahjong\
>nul 2>&1 move /y majs101b.zip .\mahjong\
>nul 2>&1 move /y marukin.zip .\mahjong\
>nul 2>&1 move /y mayumi.zip .\mahjong\
>nul 2>&1 move /y mcnpshnt.zip .\mahjong\
>nul 2>&1 move /y mcontest.zip .\mahjong\
>nul 2>&1 move /y mfunclub.zip .\mahjong\
>nul 2>&1 move /y mgakuen.zip .\mahjong\
>nul 2>&1 move /y mgakuen2.zip .\mahjong\
>nul 2>&1 move /y mgmen89.zip .\mahjong\
>nul 2>&1 move /y mhgaiden.zip .\mahjong\
>nul 2>&1 move /y minasan.zip .\mahjong\
>nul 2>&1 move /y mj4simai.zip .\mahjong\
>nul 2>&1 move /y mjanbari.zip .\mahjong\
>nul 2>&1 move /y mjangels.zip .\mahjong\
>nul 2>&1 move /y mjcamera.zip .\mahjong\
>nul 2>&1 move /y mjclinic.zip .\mahjong\
>nul 2>&1 move /y mjderngr.zip .\mahjong\
>nul 2>&1 move /y mjdialq2.zip .\mahjong\
>nul 2>&1 move /y mjdiplob.zip .\mahjong\
>nul 2>&1 move /y mjegolf.zip .\mahjong\
>nul 2>&1 move /y mjelct3.zip .\mahjong\
>nul 2>&1 move /y mjelct3a.zip .\mahjong\
>nul 2>&1 move /y mjelctrn.zip .\mahjong\
>nul 2>&1 move /y mjfocus.zip .\mahjong\
>nul 2>&1 move /y mjfocusm.zip .\mahjong\
>nul 2>&1 move /y mjfriday.zip .\mahjong\
>nul 2>&1 move /y mjgottsu.zip .\mahjong\
>nul 2>&1 move /y mjhokite.zip .\mahjong\
>nul 2>&1 move /y mjifb.zip .\mahjong\
>nul 2>&1 move /y mjikaga.zip .\mahjong\
>nul 2>&1 move /y mjkinjas.zip .\mahjong\
>nul 2>&1 move /y mjkjidai.zip .\mahjong\
>nul 2>&1 move /y mjkoiura.zip .\mahjong\
>nul 2>&1 move /y mjkojink.zip .\mahjong\
>nul 2>&1 move /y mjlaman.zip .\mahjong\
>nul 2>&1 move /y mjlstory.zip .\mahjong\
>nul 2>&1 move /y mjnanpaa.zip .\mahjong\
>nul 2>&1 move /y mjnanpas.zip .\mahjong\
>nul 2>&1 move /y mjnanpau.zip .\mahjong\
>nul 2>&1 move /y mjnatsu.zip .\mahjong\
>nul 2>&1 move /y mjnquesb.zip .\mahjong\
>nul 2>&1 move /y mjnquest.zip .\mahjong\
>nul 2>&1 move /y mjsikakb.zip .\mahjong\
>nul 2>&1 move /y mjsikaku.zip .\mahjong\
>nul 2>&1 move /y mjsister.zip .\mahjong\
>nul 2>&1 move /y mjuraden.zip .\mahjong\
>nul 2>&1 move /y mjyougo.zip .\mahjong\
>nul 2>&1 move /y mjyuugi.zip .\mahjong\
>nul 2>&1 move /y mjyuugia.zip .\mahjong\
>nul 2>&1 move /y mjzoomin.zip .\mahjong\
>nul 2>&1 move /y mkeibaou.zip .\mahjong\
>nul 2>&1 move /y mladyhtr.zip .\mahjong\
>nul 2>&1 move /y mmcamera.zip .\mahjong\
>nul 2>&1 move /y mmehyou.zip .\mahjong\
>nul 2>&1 move /y mrokumei.zip .\mahjong\
>nul 2>&1 move /y mscoutm.zip .\mahjong\
>nul 2>&1 move /y msjiken.zip .\mahjong\
>nul 2>&1 move /y myfairld.zip .\mahjong\
>nul 2>&1 move /y natsuiro.zip .\mahjong\
>nul 2>&1 move /y nekkyoku.zip .\mahjong\
>nul 2>&1 move /y neruton.zip .\mahjong\
>nul 2>&1 move /y ngpgal.zip .\mahjong\
>nul 2>&1 move /y nmsengen.zip .\mahjong\
>nul 2>&1 move /y ntopstar.zip .\mahjong\
>nul 2>&1 move /y ojanko2.zip .\mahjong\
>nul 2>&1 move /y ojankoc.zip .\mahjong\
>nul 2>&1 move /y ojankohs.zip .\mahjong\
>nul 2>&1 move /y ojankoy.zip .\mahjong\
>nul 2>&1 move /y ojousan.zip .\mahjong\
>nul 2>&1 move /y orangec.zip .\mahjong\
>nul 2>&1 move /y otatidai.zip .\mahjong\
>nul 2>&1 move /y otonano.zip .\mahjong\
>nul 2>&1 move /y pachiten.zip .\mahjong\
>nul 2>&1 move /y pastelgl.zip .\mahjong\
>nul 2>&1 move /y patimono.zip .\mahjong\
>nul 2>&1 move /y peepshow.zip .\mahjong\
>nul 2>&1 move /y ponchin.zip .\mahjong\
>nul 2>&1 move /y ponchina.zip .\mahjong\
>nul 2>&1 move /y psailor1.zip .\mahjong\
>nul 2>&1 move /y psailor2.zip .\mahjong\
>nul 2>&1 move /y pstadium.zip .\mahjong\
>nul 2>&1 move /y qmhayaku.zip .\mahjong\
>nul 2>&1 move /y renaiclb.zip .\mahjong\
>nul 2>&1 move /y rmhaihai.zip .\mahjong\
>nul 2>&1 move /y rmhaihib.zip .\mahjong\
>nul 2>&1 move /y rmhaijin.zip .\mahjong\
>nul 2>&1 move /y rmhaisei.zip .\mahjong\
>nul 2>&1 move /y royalmah.zip .\mahjong\
>nul 2>&1 move /y ryouran.zip .\mahjong\
>nul 2>&1 move /y sailorwr.zip .\mahjong\
>nul 2>&1 move /y sailorws.zip .\mahjong\
>nul 2>&1 move /y scandal.zip .\mahjong\
>nul 2>&1 move /y scandalm.zip .\mahjong\
>nul 2>&1 move /y secolove.zip .\mahjong\
>nul 2>&1 move /y seiha.zip .\mahjong\
>nul 2>&1 move /y seiham.zip .\mahjong\
>nul 2>&1 move /y sengokmj.zip .\mahjong\
>nul 2>&1 move /y srmp2.zip .\mahjong\
>nul 2>&1 move /y srmp3.zip .\mahjong\
>nul 2>&1 move /y srmp4.zip .\mahjong\
>nul 2>&1 move /y srmp4o.zip .\mahjong\
>nul 2>&1 move /y srmp5.zip .\mahjong\
>nul 2>&1 move /y srmp7.zip .\mahjong\
>nul 2>&1 move /y suchipi.zip .\mahjong\
>nul 2>&1 move /y suzume.zip .\mahjong\
>nul 2>&1 move /y teljan.zip .\mahjong\
>nul 2>&1 move /y telmahjn.zip .\mahjong\
>nul 2>&1 move /y themj.zip .\mahjong\
>nul 2>&1 move /y tmmjprd.zip .\mahjong\
>nul 2>&1 move /y tokimbsj.zip .\mahjong\
>nul 2>&1 move /y tokyogal.zip .\mahjong\
>nul 2>&1 move /y tontonb.zip .\mahjong\
>nul 2>&1 move /y triplew1.zip .\mahjong\
>nul 2>&1 move /y triplew2.zip .\mahjong\
>nul 2>&1 move /y ttmahjng.zip .\mahjong\
>nul 2>&1 move /y uchuuai.zip .\mahjong\
>nul 2>&1 move /y ultramhm.zip .\mahjong\
>nul 2>&1 move /y vanilla.zip .\mahjong\
>nul 2>&1 move /y vipclub.zip .\mahjong\
>nul 2>&1 move /y vitaminc.zip .\mahjong\
>nul 2>&1 move /y vmahjong.zip .\mahjong\
>nul 2>&1 move /y vsmahjng.zip .\mahjong\
>nul 2>&1 move /y yarunara.zip .\mahjong\
>nul 2>&1 move /y yujan.zip .\mahjong\

md quiz
>nul 2>&1 move /y atehate.zip .\quiz\
>nul 2>&1 move /y bigbucks.zip .\quiz\
>nul 2>&1 move /y bkrtmaq.zip .\quiz\
>nul 2>&1 move /y cworld.zip .\quiz\
>nul 2>&1 move /y cworld2j.zip .\quiz\
>nul 2>&1 move /y fax.zip .\quiz\
>nul 2>&1 move /y findout.zip .\quiz\
>nul 2>&1 move /y gakupara.zip .\quiz\
>nul 2>&1 move /y gekiretu.zip .\quiz\
>nul 2>&1 move /y gt102b.zip .\quiz\
>nul 2>&1 move /y gt102c.zip .\quiz\
>nul 2>&1 move /y gt102c1.zip .\quiz\
>nul 2>&1 move /y gt102c2.zip .\quiz\
>nul 2>&1 move /y gt102c3.zip .\quiz\
>nul 2>&1 move /y gt103.zip .\quiz\
>nul 2>&1 move /y gt103a.zip .\quiz\
>nul 2>&1 move /y gt103a1.zip .\quiz\
>nul 2>&1 move /y gt103a2.zip .\quiz\
>nul 2>&1 move /y gt103asa.zip .\quiz\
>nul 2>&1 move /y gt103asx.zip .\quiz\
>nul 2>&1 move /y gt5.zip .\quiz\
>nul 2>&1 move /y gt507uk.zip .\quiz\
>nul 2>&1 move /y hangman.zip .\quiz\
>nul 2>&1 move /y hatena.zip .\quiz\
>nul 2>&1 move /y hayaosi1.zip .\quiz\
>nul 2>&1 move /y hotdebut.zip .\quiz\
>nul 2>&1 move /y hyhoo.zip .\quiz\
>nul 2>&1 move /y hyhoo2.zip .\quiz\
>nul 2>&1 move /y introdon.zip .\quiz\
>nul 2>&1 move /y inufuku.zip .\quiz\
>nul 2>&1 move /y keithlcy.zip .\quiz\
>nul 2>&1 move /y kirameki.zip .\quiz\
>nul 2>&1 move /y marukodq.zip .\quiz\
>nul 2>&1 move /y mdhorse.zip .\quiz\
>nul 2>&1 move /y myangel.zip .\quiz\
>nul 2>&1 move /y myangel2.zip .\quiz\
>nul 2>&1 move /y myangel3.zip .\quiz\
>nul 2>&1 move /y nametune.zip .\quiz\
>nul 2>&1 move /y nettoqc.zip .\quiz\
>nul 2>&1 move /y nouryoku.zip .\quiz\
>nul 2>&1 move /y popspops.zip .\quiz\
>nul 2>&1 move /y profpac.zip .\quiz\
>nul 2>&1 move /y qad.zip .\quiz\
>nul 2>&1 move /y qadj.zip .\quiz\
>nul 2>&1 move /y qcrayon.zip .\quiz\
>nul 2>&1 move /y qdrmfgp.zip .\quiz\
>nul 2>&1 move /y qdrmfgp2.zip .\quiz\
>nul 2>&1 move /y qgakumon.zip .\quiz\
>nul 2>&1 move /y qgh.zip .\quiz\
>nul 2>&1 move /y qjinsei.zip .\quiz\
>nul 2>&1 move /y qndream.zip .\quiz\
>nul 2>&1 move /y qrouka.zip .\quiz\
>nul 2>&1 move /y qsangoku.zip .\quiz\
>nul 2>&1 move /y qsww.zip .\quiz\
>nul 2>&1 move /y qtheater.zip .\quiz\
>nul 2>&1 move /y qtono1.zip .\quiz\
>nul 2>&1 move /y qtono2.zip .\quiz\
>nul 2>&1 move /y qtorimon.zip .\quiz\
>nul 2>&1 move /y quaquiz2.zip .\quiz\
>nul 2>&1 move /y quiz18k.zip .\quiz\
>nul 2>&1 move /y quiz365.zip .\quiz\
>nul 2>&1 move /y quiz365t.zip .\quiz\
>nul 2>&1 move /y quizchq.zip .\quiz\
>nul 2>&1 move /y quizchql.zip .\quiz\
>nul 2>&1 move /y quizdai2.zip .\quiz\
>nul 2>&1 move /y quizdais.zip .\quiz\
>nul 2>&1 move /y quizdna.zip .\quiz\
>nul 2>&1 move /y quizf1.zip .\quiz\
>nul 2>&1 move /y quizhq.zip .\quiz\
>nul 2>&1 move /y quizhuhu.zip .\quiz\
>nul 2>&1 move /y quizkof.zip .\quiz\
>nul 2>&1 move /y quizmeku.zip .\quiz\
>nul 2>&1 move /y quizmoon.zip .\quiz\
>nul 2>&1 move /y quizpani.zip .\quiz\
>nul 2>&1 move /y quiztou.zip .\quiz\
>nul 2>&1 move /y quiztvqq.zip .\quiz\
>nul 2>&1 move /y qzchikyu.zip .\quiz\
>nul 2>&1 move /y qzkklgy2.zip .\quiz\
>nul 2>&1 move /y qzkklogy.zip .\quiz\
>nul 2>&1 move /y qzquest.zip .\quiz\
>nul 2>&1 move /y qzshowby.zip .\quiz\
>nul 2>&1 move /y rocktrv2.zip .\quiz\
>nul 2>&1 move /y ryorioh.zip .\quiz\
>nul 2>&1 move /y sextriv1.zip .\quiz\
>nul 2>&1 move /y sextriv2.zip .\quiz\
>nul 2>&1 move /y statriv2.zip .\quiz\
>nul 2>&1 move /y statriv4.zip .\quiz\
>nul 2>&1 move /y strvmstr.zip .\quiz\
>nul 2>&1 move /y supertr2.zip .\quiz\
>nul 2>&1 move /y supertr3.zip .\quiz\
>nul 2>&1 move /y triviabb.zip .\quiz\
>nul 2>&1 move /y triviag1.zip .\quiz\
>nul 2>&1 move /y triviag2.zip .\quiz\
>nul 2>&1 move /y triviasp.zip .\quiz\
>nul 2>&1 move /y triviayp.zip .\quiz\
>nul 2>&1 move /y trivquiz.zip .\quiz\
>nul 2>&1 move /y weddingr.zip .\quiz\
>nul 2>&1 move /y wfortuna.zip .\quiz\
>nul 2>&1 move /y wfortune.zip .\quiz\
>nul 2>&1 move /y whizquiz.zip .\quiz\
>nul 2>&1 move /y xday2.zip .\quiz\
>nul 2>&1 move /y yesnoj.zip .\quiz\
>nul 2>&1 move /y yuyugogo.zip .\quiz\

