@echo off
title "MAMEoXtras_[Mar-20-2023].xml" ^| Build: Mon 03/20/2023
echo.=====================================================
echo. This script will MOVE matched .zip files   
echo.=====================================================
choice /m "Continue?"
if %errorlevel% equ 2 exit
cls&echo. Creating folders and moving files...
md mature
>nul 2>&1 move /y 3kokushi.zip .\mature\
>nul 2>&1 move /y 47pie2.zip .\mature\
>nul 2>&1 move /y 47pie2o.zip .\mature\
>nul 2>&1 move /y 7jigen.zip .\mature\
>nul 2>&1 move /y 7toitsu.zip .\mature\
>nul 2>&1 move /y akiss.zip .\mature\
>nul 2>&1 move /y apparel.zip .\mature\
>nul 2>&1 move /y av2mj1bb.zip .\mature\
>nul 2>&1 move /y av2mj2rg.zip .\mature\
>nul 2>&1 move /y bakatono.zip .\mature\
>nul 2>&1 move /y bakuhatu.zip .\mature\
>nul 2>&1 move /y bananadr.zip .\mature\
>nul 2>&1 move /y bballs.zip .\mature\
>nul 2>&1 move /y bigtwin.zip .\mature\
>nul 2>&1 move /y bijokkog.zip .\mature\
>nul 2>&1 move /y bijokkoy.zip .\mature\
>nul 2>&1 move /y blandia.zip .\mature\
>nul 2>&1 move /y blandiap.zip .\mature\
>nul 2>&1 move /y blckgalb.zip .\mature\
>nul 2>&1 move /y blockgal.zip .\mature\
>nul 2>&1 move /y bubl2000.zip .\mature\
>nul 2>&1 move /y cabaret.zip .\mature\
>nul 2>&1 move /y cannball.zip .\mature\
>nul 2>&1 move /y ccasino.zip .\mature\
>nul 2>&1 move /y chinmoku.zip .\mature\
>nul 2>&1 move /y citylove.zip .\mature\
>nul 2>&1 move /y club90s.zip .\mature\
>nul 2>&1 move /y club90sa.zip .\mature\
>nul 2>&1 move /y cmehyou.zip .\mature\
>nul 2>&1 move /y crystal2.zip .\mature\
>nul 2>&1 move /y crystalg.zip .\mature\
>nul 2>&1 move /y daiyogen.zip .\mature\
>nul 2>&1 move /y dakkochn.zip .\mature\
>nul 2>&1 move /y danceyes.zip .\mature\
>nul 2>&1 move /y danchih.zip .\mature\
>nul 2>&1 move /y dblpoint.zip .\mature\
>nul 2>&1 move /y ddenlovr.zip .\mature\
>nul 2>&1 move /y dokyusei.zip .\mature\
>nul 2>&1 move /y dokyusp.zip .\mature\
>nul 2>&1 move /y dondenmj.zip .\mature\
>nul 2>&1 move /y drgnwrld.zip .\mature\
>nul 2>&1 move /y drgpunch.zip .\mature\
>nul 2>&1 move /y ejanhs.zip .\mature\
>nul 2>&1 move /y excelsr.zip .\mature\
>nul 2>&1 move /y fantasia.zip .\mature\
>nul 2>&1 move /y fantsia2.zip .\mature\
>nul 2>&1 move /y fantsy95.zip .\mature\
>nul 2>&1 move /y finalbny.zip .\mature\
>nul 2>&1 move /y findlove.zip .\mature\
>nul 2>&1 move /y fromanc2.zip .\mature\
>nul 2>&1 move /y fromanc4.zip .\mature\
>nul 2>&1 move /y fromance.zip .\mature\
>nul 2>&1 move /y fromancr.zip .\mature\
>nul 2>&1 move /y funybubl.zip .\mature\
>nul 2>&1 move /y gakusai.zip .\mature\
>nul 2>&1 move /y gakusai2.zip .\mature\
>nul 2>&1 move /y gal10ren.zip .\mature\
>nul 2>&1 move /y galhustl.zip .\mature\
>nul 2>&1 move /y galkaika.zip .\mature\
>nul 2>&1 move /y galkoku.zip .\mature\
>nul 2>&1 move /y galpandx.zip .\mature\
>nul 2>&1 move /y galpani2.zip .\mature\
>nul 2>&1 move /y galpani3.zip .\mature\
>nul 2>&1 move /y galpani4.zip .\mature\
>nul 2>&1 move /y galpanib.zip .\mature\
>nul 2>&1 move /y galpanic.zip .\mature\
>nul 2>&1 move /y galpanis.zip .\mature\
>nul 2>&1 move /y galpans2.zip .\mature\
>nul 2>&1 move /y galspnbl.zip .\mature\
>nul 2>&1 move /y gangonta.zip .\mature\
>nul 2>&1 move /y gfire2.zip .\mature\
>nul 2>&1 move /y gionbana.zip .\mature\
>nul 2>&1 move /y glass.zip .\mature\
>nul 2>&1 move /y glass94.zip .\mature\
>nul 2>&1 move /y gpan2qiz.zip .\mature\
>nul 2>&1 move /y grndtour.zip .\mature\
>nul 2>&1 move /y grtwall.zip .\mature\
>nul 2>&1 move /y gt102c3.zip .\mature\
>nul 2>&1 move /y gt103a.zip .\mature\
>nul 2>&1 move /y gt103a1.zip .\mature\
>nul 2>&1 move /y gt103a2.zip .\mature\
>nul 2>&1 move /y gt103asa.zip .\mature\
>nul 2>&1 move /y gt103asx.zip .\mature\
>nul 2>&1 move /y gumbo.zip .\mature\
>nul 2>&1 move /y gundeala.zip .\mature\
>nul 2>&1 move /y gundealr.zip .\mature\
>nul 2>&1 move /y gundealt.zip .\mature\
>nul 2>&1 move /y gundl94.zip .\mature\
>nul 2>&1 move /y hanakanz.zip .\mature\
>nul 2>&1 move /y hanamai.zip .\mature\
>nul 2>&1 move /y hanamomo.zip .\mature\
>nul 2>&1 move /y hanaoji.zip .\mature\
>nul 2>&1 move /y hexa.zip .\mature\
>nul 2>&1 move /y hgkairak.zip .\mature\
>nul 2>&1 move /y hnayayoi.zip .\mature\
>nul 2>&1 move /y hnfubuki.zip .\mature\
>nul 2>&1 move /y hnkochou.zip .\mature\
>nul 2>&1 move /y hotbubl.zip .\mature\
>nul 2>&1 move /y hotgmck.zip .\mature\
>nul 2>&1 move /y hotgmck3.zip .\mature\
>nul 2>&1 move /y hotpinbl.zip .\mature\
>nul 2>&1 move /y hourouki.zip .\mature\
>nul 2>&1 move /y housemn2.zip .\mature\
>nul 2>&1 move /y housemnq.zip .\mature\
>nul 2>&1 move /y hyhoo.zip .\mature\
>nul 2>&1 move /y hyhoo2.zip .\mature\
>nul 2>&1 move /y hyouban.zip .\mature\
>nul 2>&1 move /y hypreac2.zip .\mature\
>nul 2>&1 move /y hypreact.zip .\mature\
>nul 2>&1 move /y idhimitu.zip .\mature\
>nul 2>&1 move /y idolmj.zip .\mature\
>nul 2>&1 move /y iemoto.zip .\mature\
>nul 2>&1 move /y imekura.zip .\mature\
>nul 2>&1 move /y inca.zip .\mature\
>nul 2>&1 move /y janjans1.zip .\mature\
>nul 2>&1 move /y janshin.zip .\mature\
>nul 2>&1 move /y jantouki.zip .\mature\
>nul 2>&1 move /y jjparad2.zip .\mature\
>nul 2>&1 move /y jjparads.zip .\mature\
>nul 2>&1 move /y jogakuen.zip .\mature\
>nul 2>&1 move /y kaguya.zip .\mature\
>nul 2>&1 move /y kakumei.zip .\mature\
>nul 2>&1 move /y kakumei2.zip .\mature\
>nul 2>&1 move /y kanatuen.zip .\mature\
>nul 2>&1 move /y kirarast.zip .\mature\
>nul 2>&1 move /y kof2k4se.zip .\mature\
>nul 2>&1 move /y koikois2.zip .\mature\
>nul 2>&1 move /y koinomp.zip .\mature\
>nul 2>&1 move /y korinai.zip .\mature\
>nul 2>&1 move /y ladykill.zip .\mature\
>nul 2>&1 move /y lastfero.zip .\mature\
>nul 2>&1 move /y lemnangl.zip .\mature\
>nul 2>&1 move /y lvcards.zip .\mature\
>nul 2>&1 move /y lvgirl94.zip .\mature\
>nul 2>&1 move /y maddonna.zip .\mature\
>nul 2>&1 move /y maddonnb.zip .\mature\
>nul 2>&1 move /y magix.zip .\mature\
>nul 2>&1 move /y mahretsu.zip .\mature\
>nul 2>&1 move /y maiko.zip .\mature\
>nul 2>&1 move /y majs101b.zip .\mature\
>nul 2>&1 move /y marukin.zip .\mature\
>nul 2>&1 move /y matchit.zip .\mature\
>nul 2>&1 move /y maya.zip .\mature\
>nul 2>&1 move /y mayumi.zip .\mature\
>nul 2>&1 move /y mchampdx.zip .\mature\
>nul 2>&1 move /y mchampdxa.zip .\mature\
>nul 2>&1 move /y mcnpshnt.zip .\mature\
>nul 2>&1 move /y mcontest.zip .\mature\
>nul 2>&1 move /y mfunclub.zip .\mature\
>nul 2>&1 move /y mgakuen.zip .\mature\
>nul 2>&1 move /y mgakuen2.zip .\mature\
>nul 2>&1 move /y mgmen89.zip .\mature\
>nul 2>&1 move /y mhgaiden.zip .\mature\
>nul 2>&1 move /y missb2.zip .\mature\
>nul 2>&1 move /y missmw96.zip .\mature\
>nul 2>&1 move /y missw96.zip .\mature\
>nul 2>&1 move /y mj4simai.zip .\mature\
>nul 2>&1 move /y mjanbari.zip .\mature\
>nul 2>&1 move /y mjangels.zip .\mature\
>nul 2>&1 move /y mjcamera.zip .\mature\
>nul 2>&1 move /y mjclinic.zip .\mature\
>nul 2>&1 move /y mjderngr.zip .\mature\
>nul 2>&1 move /y mjdialq2.zip .\mature\
>nul 2>&1 move /y mjdiplob.zip .\mature\
>nul 2>&1 move /y mjegolf.zip .\mature\
>nul 2>&1 move /y mjelct3.zip .\mature\
>nul 2>&1 move /y mjelct3a.zip .\mature\
>nul 2>&1 move /y mjelctrn.zip .\mature\
>nul 2>&1 move /y mjfocus.zip .\mature\
>nul 2>&1 move /y mjfocusm.zip .\mature\
>nul 2>&1 move /y mjfriday.zip .\mature\
>nul 2>&1 move /y mjgottsu.zip .\mature\
>nul 2>&1 move /y mjhokite.zip .\mature\
>nul 2>&1 move /y mjikaga.zip .\mature\
>nul 2>&1 move /y mjkinjas.zip .\mature\
>nul 2>&1 move /y mjkjidai.zip .\mature\
>nul 2>&1 move /y mjkoiura.zip .\mature\
>nul 2>&1 move /y mjkojink.zip .\mature\
>nul 2>&1 move /y mjlaman.zip .\mature\
>nul 2>&1 move /y mjlstory.zip .\mature\
>nul 2>&1 move /y mjnanpaa.zip .\mature\
>nul 2>&1 move /y mjnanpas.zip .\mature\
>nul 2>&1 move /y mjnanpau.zip .\mature\
>nul 2>&1 move /y mjnatsu.zip .\mature\
>nul 2>&1 move /y mjnquesb.zip .\mature\
>nul 2>&1 move /y mjnquest.zip .\mature\
>nul 2>&1 move /y mjsikakb.zip .\mature\
>nul 2>&1 move /y mjsikaku.zip .\mature\
>nul 2>&1 move /y mjsister.zip .\mature\
>nul 2>&1 move /y mjuraden.zip .\mature\
>nul 2>&1 move /y mjyougo.zip .\mature\
>nul 2>&1 move /y mjyuugi.zip .\mature\
>nul 2>&1 move /y mjyuugia.zip .\mature\
>nul 2>&1 move /y mjzoomin.zip .\mature\
>nul 2>&1 move /y mkeibaou.zip .\mature\
>nul 2>&1 move /y mladyhtr.zip .\mature\
>nul 2>&1 move /y mmcamera.zip .\mature\
>nul 2>&1 move /y mmehyou.zip .\mature\
>nul 2>&1 move /y moegonta.zip .\mature\
>nul 2>&1 move /y mrokumei.zip .\mature\
>nul 2>&1 move /y mscoutm.zip .\mature\
>nul 2>&1 move /y msjiken.zip .\mature\
>nul 2>&1 move /y mspuzzle.zip .\mature\
>nul 2>&1 move /y myfairld.zip .\mature\
>nul 2>&1 move /y natsuiro.zip .\mature\
>nul 2>&1 move /y nekkyoku.zip .\mature\
>nul 2>&1 move /y neruton.zip .\mature\
>nul 2>&1 move /y newfant.zip .\mature\
>nul 2>&1 move /y news.zip .\mature\
>nul 2>&1 move /y ngpgal.zip .\mature\
>nul 2>&1 move /y niyanpai.zip .\mature\
>nul 2>&1 move /y nmsengen.zip .\mature\
>nul 2>&1 move /y ntopstar.zip .\mature\
>nul 2>&1 move /y ojanko2.zip .\mature\
>nul 2>&1 move /y ojankoc.zip .\mature\
>nul 2>&1 move /y ojankohs.zip .\mature\
>nul 2>&1 move /y ojankoy.zip .\mature\
>nul 2>&1 move /y ojousan.zip .\mature\
>nul 2>&1 move /y onetwo.zip .\mature\
>nul 2>&1 move /y orangec.zip .\mature\
>nul 2>&1 move /y otatidai.zip .\mature\
>nul 2>&1 move /y otonano.zip .\mature\
>nul 2>&1 move /y pachiten.zip .\mature\
>nul 2>&1 move /y pairlove.zip .\mature\
>nul 2>&1 move /y pairs.zip .\mature\
>nul 2>&1 move /y pairsa.zip .\mature\
>nul 2>&1 move /y pairsten.zip .\mature\
>nul 2>&1 move /y paradise.zip .\mature\
>nul 2>&1 move /y pastelgl.zip .\mature\
>nul 2>&1 move /y patimono.zip .\mature\
>nul 2>&1 move /y pcktgal.zip .\mature\
>nul 2>&1 move /y pcktgal2.zip .\mature\
>nul 2>&1 move /y pcktgalb.zip .\mature\
>nul 2>&1 move /y peekaboo.zip .\mature\
>nul 2>&1 move /y peepshow.zip .\mature\
>nul 2>&1 move /y perestrf.zip .\mature\
>nul 2>&1 move /y perestro.zip .\mature\
>nul 2>&1 move /y pipibibi.zip .\mature\
>nul 2>&1 move /y pipibibs.zip .\mature\
>nul 2>&1 move /y pkgnsh.zip .\mature\
>nul 2>&1 move /y pkgnshdx.zip .\mature\
>nul 2>&1 move /y pkladiel.zip .\mature\
>nul 2>&1 move /y pkladies.zip .\mature\
>nul 2>&1 move /y pktgaldb.zip .\mature\
>nul 2>&1 move /y pktgaldj.zip .\mature\
>nul 2>&1 move /y pktgaldx.zip .\mature\
>nul 2>&1 move /y plgirls.zip .\mature\
>nul 2>&1 move /y plgirls2.zip .\mature\
>nul 2>&1 move /y ponchin.zip .\mature\
>nul 2>&1 move /y ponchina.zip .\mature\
>nul 2>&1 move /y popbingo.zip .\mature\
>nul 2>&1 move /y primella.zip .\mature\
>nul 2>&1 move /y prtytime.zip .\mature\
>nul 2>&1 move /y psailor1.zip .\mature\
>nul 2>&1 move /y psailor2.zip .\mature\
>nul 2>&1 move /y pstadium.zip .\mature\
>nul 2>&1 move /y pushman.zip .\mature\
>nul 2>&1 move /y pushmans.zip .\mature\
>nul 2>&1 move /y puzznic.zip .\mature\
>nul 2>&1 move /y qmhayaku.zip .\mature\
>nul 2>&1 move /y quiz18k.zip .\mature\
>nul 2>&1 move /y realbrk.zip .\mature\
>nul 2>&1 move /y realbrkb.zip .\mature\
>nul 2>&1 move /y renaiclb.zip .\mature\
>nul 2>&1 move /y rmhaihai.zip .\mature\
>nul 2>&1 move /y rmhaihib.zip .\mature\
>nul 2>&1 move /y rmhaijin.zip .\mature\
>nul 2>&1 move /y rmhaisei.zip .\mature\
>nul 2>&1 move /y roldfrga.zip .\mature\
>nul 2>&1 move /y roldfrog.zip .\mature\
>nul 2>&1 move /y rongrong.zip .\mature\
>nul 2>&1 move /y sadari.zip .\mature\
>nul 2>&1 move /y sailorwr.zip .\mature\
>nul 2>&1 move /y sailorws.zip .\mature\
>nul 2>&1 move /y scandal.zip .\mature\
>nul 2>&1 move /y scandalm.zip .\mature\
>nul 2>&1 move /y secolove.zip .\mature\
>nul 2>&1 move /y seiha.zip .\mature\
>nul 2>&1 move /y seiham.zip .\mature\
>nul 2>&1 move /y sextriv1.zip .\mature\
>nul 2>&1 move /y sextriv2.zip .\mature\
>nul 2>&1 move /y sexyparo.zip .\mature\
>nul 2>&1 move /y shisen.zip .\mature\
>nul 2>&1 move /y sichuan2.zip .\mature\
>nul 2>&1 move /y sichuana.zip .\mature\
>nul 2>&1 move /y sos.zip .\mature\
>nul 2>&1 move /y spbactn.zip .\mature\
>nul 2>&1 move /y spbactnj.zip .\mature\
>nul 2>&1 move /y splash.zip .\mature\
>nul 2>&1 move /y spool3.zip .\mature\
>nul 2>&1 move /y spool3i.zip .\mature\
>nul 2>&1 move /y sprtmtch.zip .\mature\
>nul 2>&1 move /y srmp2.zip .\mature\
>nul 2>&1 move /y srmp3.zip .\mature\
>nul 2>&1 move /y srmp4.zip .\mature\
>nul 2>&1 move /y srmp4o.zip .\mature\
>nul 2>&1 move /y srmp7.zip .\mature\
>nul 2>&1 move /y sshanghb.zip .\mature\
>nul 2>&1 move /y ssingles.zip .\mature\
>nul 2>&1 move /y stoffy.zip .\mature\
>nul 2>&1 move /y streakng.zip .\mature\
>nul 2>&1 move /y suchipi.zip .\mature\
>nul 2>&1 move /y supertr2.zip .\mature\
>nul 2>&1 move /y supertr3.zip .\mature\
>nul 2>&1 move /y suzume.zip .\mature\
>nul 2>&1 move /y sxyreact.zip .\mature\
>nul 2>&1 move /y teljan.zip .\mature\
>nul 2>&1 move /y telmahjn.zip .\mature\
>nul 2>&1 move /y tgtball.zip .\mature\
>nul 2>&1 move /y tgtballa.zip .\mature\
>nul 2>&1 move /y themj.zip .\mature\
>nul 2>&1 move /y tmmjprd.zip .\mature\
>nul 2>&1 move /y tokimbsj.zip .\mature\
>nul 2>&1 move /y tokyogal.zip .\mature\
>nul 2>&1 move /y tontonb.zip .\mature\
>nul 2>&1 move /y triplew1.zip .\mature\
>nul 2>&1 move /y triplew2.zip .\mature\
>nul 2>&1 move /y uchuuai.zip .\mature\
>nul 2>&1 move /y ultramhm.zip .\mature\
>nul 2>&1 move /y untoucha.zip .\mature\
>nul 2>&1 move /y usg185.zip .\mature\
>nul 2>&1 move /y usg252.zip .\mature\
>nul 2>&1 move /y usg32.zip .\mature\
>nul 2>&1 move /y usg82.zip .\mature\
>nul 2>&1 move /y usg83.zip .\mature\
>nul 2>&1 move /y usg83x.zip .\mature\
>nul 2>&1 move /y vanilla.zip .\mature\
>nul 2>&1 move /y vipclub.zip .\mature\
>nul 2>&1 move /y vitaminc.zip .\mature\
>nul 2>&1 move /y vmahjong.zip .\mature\
>nul 2>&1 move /y whoopee.zip .\mature\
>nul 2>&1 move /y wiggie.zip .\mature\
>nul 2>&1 move /y yarunara.zip .\mature\
>nul 2>&1 move /y zerozone.zip .\mature\

